Feature/PA-43 implementation of project documentation user interface definition
DiPA-Projekt/projektassistent pull request #103
Opened 2021-04-12 09:58 UTC by Bock4Soft

2021-04-12 18:43 UTC, deleonio requested changes

2021-04-12 18:43 UTC, deleonio commented on client/src/components/home/component.tsx
> +      <>
not needed

2021-04-12 18:43 UTC, deleonio commented on client/src/components/projekthandbuch/documentation/component.tsx
> +      <>
Fragement not needed

2021-04-12 18:43 UTC, deleonio commented on client/src/components/projekthandbuch/documentation/anchorList/component.tsx
> +    <>
Fragment not needed.

2021-04-12 18:44 UTC, deleonio commented
Der PR ist extrem groß.

2021-04-13 09:37 UTC, Bock4Soft commented
> Der PR ist extrem groß.

Echt? Ich hätte so "mittel" gesagt ;D

2021-04-15 03:10 UTC, deleonio commented
Lass uns den mal **kurz** zusammen durchgehen, dass wäre cool.

2021-04-15 07:16 UTC, Bock4Soft commented
> Lass uns den mal **kurz** zusammen durchgehen, dass wäre cool.

Super gerne... wann passt es dir? Ich bin heute sehr flexibel

2021-04-16 08:48 UTC, deleonio commented
Kurzes Nachgespräch machen wir noch einmal nach dem Merge.

2021-04-27 09:57 UTC, merged